"""Use MutableList for items

Revision ID: d11d0fc0a8a8
Revises: e41c137c67aa
Create Date: 2024-11-28 16:26:23.245718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd11d0fc0a8a8'
down_revision: Union[str, None] = 'e41c137c67aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.NUMERIC(), nullable=False),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('items', sqlite.JSON(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###
