"""Add items field as JSON

Revision ID: e41c137c67aa
Revises: 
Create Date: 2024-11-28 14:28:57.617749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41c137c67aa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.NUMERIC(), nullable=False),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('items', sa.VARCHAR(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###
