"""Automatically calculate total price

Revision ID: ed232ae263a5
Revises: 6d4937347ad8
Create Date: 2024-11-28 17:54:00.769189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'ed232ae263a5'
down_revision: Union[str, None] = '6d4937347ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('order_id', sa.NUMERIC(), nullable=False),
    sa.Column('customer_id', sa.NUMERIC(), nullable=False),
    sa.Column('items', sqlite.JSON(), nullable=False),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=10), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###
