"""Initial migration

Revision ID: 8cb825b7e37e
Revises: 33abefe81181
Create Date: 2024-12-17 14:23:42.860324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cb825b7e37e'
down_revision: Union[str, None] = '33abefe81181'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False, comment="User's first name."),
    sa.Column('last_name', sa.String(length=50), nullable=False, comment="User's last name."),
    sa.Column('email', sa.String(length=100), nullable=False, comment='Unique user email address.'),
    sa.Column('hashed_password', sa.String(length=128), nullable=False, comment='Hashed user password.'),
    sa.Column('location', sa.String(length=100), nullable=False, comment="User's location."),
    sa.Column('photo_url', sa.String(length=250), nullable=True, comment='Optional photo URL for the user.'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='Optional phone number.'),
    sa.Column('store_name', sa.String(length=100), nullable=True, comment='Optional store name for sellers.'),
    sa.Column('role', sa.Enum('merchant', 'buyer', 'admin', name='roletype'), nullable=False, comment="User role. Default is 'buyer'."),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Indicates if the user is active.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft delete timestamp.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
